app = "fullstack3-crimson-field-4603"

[build]
  # Optional: define custom builder if needed
  # builder = "paketobuildpacks/builder:base"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

